# Generated by Django 3.1.2 on 2021-02-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_location',
            field=models.JSONField(null=True),
        ),
    ]
